cargo-features = ["edition2024"]

[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
syn = "2.0.66"
quote = "1.0.36"

[lib]
proc-macro = true
